import { Geist, Geist_Mono } from "next/font/google";
import localFont from 'next/font/local'; // <-- Make sure this line exists!
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 1. Configure your Heading Font (e.g., Clash Display)
const headingFont = localFont({
  src: './fonts/Zina-Regular.woff2',
  // src: './fonts/Recia-Regular.woff2',
  variable: '--font-heading', // Defines the CSS variable name
  display: 'swap',
})

// 2. Configure your Body Font (e.g., Satoshi)
const bodyFont = localFont({
  src: './fonts/Recia-Regular.woff2',
  // src: './fonts/Zina-Regular.woff2',
  variable: '--font-body',
  display: 'swap',
})

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${headingFont.variable} ${bodyFont.variable} ${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>
        <main className="mt-18 ">
        {children}
        </main>
        <Toaster />
      </body>
    </html>
  );
}
